---
# RBAC for Oracle SQLcl MCPServer init container
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oracle-sqlcl-oracle-wait
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oracle-sqlcl-oracle-wait
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: oracle-sqlcl-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: oracle-sqlcl-oracle-wait
